# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_shrinksv_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_shrinksv_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_shrinksv_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_shrinksv_rcpparma_bothproducts`, x)
}

cholesky_tridiagonal <- function(omega_diag, omega_offdiag) {
    .Call(`_shrinksv_cholesky_tridiagonal`, omega_diag, omega_offdiag)
}

forward_algorithm <- function(chol_diag, chol_offdiag, covector) {
    .Call(`_shrinksv_forward_algorithm`, chol_diag, chol_offdiag, covector)
}

backward_algorithm <- function(chol_diag, chol_offdiag, htmp) {
    .Call(`_shrinksv_backward_algorithm`, chol_diag, chol_offdiag, htmp)
}

